version: "3"
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    shm_size: 1g
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - default
  migrate:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    networks:
      - default
    depends_on:
      - db
  admin:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 5433:8081
    networks:
      - default
    depends_on:
      - db
      - migrate
networks:
  default:
