version: "3"
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    shm_size: 1g
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - default
  migrate:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - default
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=postgres -connectRetries=60 migrate
  admin:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 5433:8081
    networks:
      - default
    depends_on:
      - db
      - migrate
  export:
    image: postgres:12.4
    volumes:
      - ./export:/tmp/export
      - ./sql:/tmp/sql
    networks:
      - default
    depends_on:
      - db
      - migrate
    command: sh -c 'sleep 10 && psql postgres://postgres:postgres@db:5432/postgres?sslmode=disable -f /tmp/sql/ExportAddressView.sql'
networks:
  default:
