name: pipeline
on:
  push:
    branches:
      - master
jobs:
  V202108:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: migrate
        run: |
          docker-compose -f tasks/V202108/docker-compose.yml build migrate
          docker-compose -f tasks/V202108/docker-compose.yml run migrate
          docker-compose -f tasks/V202108/docker-compose.yml down
