name: pipeline
on:
  push:
    branches:
      - master
jobs:
  V202108:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: migrate
        run: |
          docker-compose -f tasks/V202108/docker-compose.yml build migrate
          docker-compose -f tasks/V202108/docker-compose.yml run migrate
      - name: export
        run: |
          docker-compose -f tasks/V202108/docker-compose.yml build export
          docker-compose -f tasks/V202108/docker-compose.yml run export
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: V202108_${{ github.sha }}
          path: tasks/V202108/export
