name: pipeline
on:
  push:

jobs:
  V202111:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: migrate
        run: |
          docker-compose -f tasks/V202111/docker-compose.yml build migrate
          docker-compose -f tasks/V202111/docker-compose.yml run migrate
      - name: export
        run: |
          docker-compose -f tasks/V202111/docker-compose.yml build export
          docker-compose -f tasks/V202111/docker-compose.yml run export
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tasks/V202111/export/address_view_vic.csv
            tasks/V202111/export/address_view_nsw.csv
            tasks/V202111/export/address_view_qld.csv
            tasks/V202111/export/address_view_sa.csv
            tasks/V202111/export/address_view_wa.csv
            tasks/V202111/export/address_view_tas.csv
            tasks/V202111/export/address_view_nt.csv
            tasks/V202111/export/address_view_ot.csv
            tasks/V202111/export/address_view_ot.csv
